collections:
    authors:
        output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

id_google_analytics:
disqus_url:
title: surlescocottes
description: ride, dev and other stories
url: https://surlescocottes.xyz
locale: fr

social:
  linkedin: yannickfrancois
  github: YannickDurden
  instagram: yannick_durden
  strava: /16018371

header:
  title: surlescocottes
  subtitle: ride, dev & other stories

footer:
  text: Yannick

about:
  username: Yannick
  subtitle: curieux

nav:
  home:
  categories:
  about:

index:
    title: Nouvelles

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

permalink: /:title/

paginate: 4
paginate_path: "/page:num/"